stages:
  - test
  - notify

before_script:
 - pwd

Execute Build:
 image: atlassianlabs/docker-node-jdk-chrome-firefox:latest
 stage: test
 script:
  - pwd
  - npm install
  - npm run testV2 ${CI_BUILD_REF_NAME}
  - npm run publishV2 ${CI_BUILD_REF_NAME}
  - cd task/HW-05/JS-HW-DASHBOARD
  - npm test

Notify Success:
 image: bash
 stage: notify
 script:
  - echo 'this is to notify success....'
 when: on_success

Notify Failure:
 image: bash
 stage: notify
 script:
  - echo 'this is to notify failure....'
 when: on_failure
